### PR TITLE
remove PWA, and put styles into its own folder

### PR DESCRIPTION
**Pull request by Odyssey346**

### CODE REVIEW

**Comment by Devnol** [comment]
Ok for the Styles but the PWA has no reason to go it's not my fault if people want my website as an app on their phone

**Comment by Odyssey346** [comment]
its stupid lmao, just get rid of it

**Comment by Devnol** [comment]
Undo the commit or I'm gonna have to close the PR

**Comment by Odyssey346** [comment]
fiiiiiiiiiiiiiiiiiiiiiiiiiiiineeeeeeeeeeeeeeeeeee

**Pull request merged**
