### PR TITLE
remove Project Segfault

### PR DESCRIPTION
**Pull request by Odyssey346**
I decided to not die

### CODE REVIEW

**Review by Devnol — CHANGES_REQUESTED** [review]
I love how this has been stale for literally 3 months yet you still didn't remove all the Project Segfault references. The text at [src/components/App.tsx#L20](https://github.com/Devnol/devnol.github.io/blob/master/src/components/App.tsx#L20) still exists. How are you expecting me to even bother reviewing a PR when you yourself haven't bothered making it?

**Comment by Odyssey346** [comment]
react is a mess

**Comment by Devnol** [comment]
Nobody's forcing you to contribute if you don't want to.

**Review by Devnol — APPROVED** [review]

**Comment by Odyssey346** [comment]
it's either this or you keep the reference it seems? now that i have fixed the issue, why don't you just press merge

**Pull request merged**
