### PR TITLE
Add Webring

### PR DESCRIPTION
**Pull request by ChelonianEgghead**
there you see just like that

### CODE REVIEW

**Comment by Oxygemo** [comment]
hmm, think we should wait until panis makes the actual site - but yeah I agree

**Comment by Oxygemo** [comment]
Autocorrect, dammit!

**Review by Oxygemo — APPROVED** [review]

**Comment by Devnol** [comment]
Aight fine

**Comment by Devnol** [comment]
aaaand it looks like crap

**Pull request merged**
