### PR TITLE
add "scroll down" text

### PR DESCRIPTION
**Pull request by Odyssey346**
Signed-off-by: Alexander Johansen <odyssey346@disroot.org>

### CODE REVIEW

**Comment by Devnol** [comment]
doesn't work wontfix

**Comment by Odyssey346** [comment]
can't you tell me why it doesn't work?

**Comment by Devnol** [comment]
it's not centered and it overlaps the mouse and I already told you I don't care anough

**Comment by Odyssey346** [comment]
Works on My Machine:tm:

**Pull request closed without merging**
