### PR TITLE
fix proejct list shit (doesnt use fucking grid)

### PR DESCRIPTION
**Pull request by akisblack**

### CODE REVIEW

**Comment by Devnol** [comment]
Why is this wrapping over? https://cdn.discordapp.com/attachments/572212126785994752/882163931437752340/unknown.png

**Comment by Devnol** [comment]
Even worse on mobile. https://cdn.discordapp.com/attachments/572212126785994752/882164286103896094/unknown.png
Akis i had a fucking reason to use grid

**Comment by akisblack** [comment]
i will fix it
wait

**Comment by akisblack** [comment]
grid sucks btw

**Pull request merged**
